import type { SeedEvent } from '../types.js';

// Era 4 (순조 ~ 순종, 1800~1910). 헤드라인.
export const ERA4_EVENTS: SeedEvent[] = [
  // 순조
  { king_id: 'sunjo', year: 1801, reign_year: 1, title_ko: '신유박해', title_hanja: '辛酉迫害',
    summary_html: '<p>천주교를 사학(邪學)으로 규정하고 이승훈·정약종·주문모 신부 등 300여 명을 처형·유배하였다. 정약용·정약전은 강진·흑산도로 귀양 갔다.</p>',
    tags: ['천주교', '박해'] },
  { king_id: 'sunjo', year: 1811, reign_year: 11, title_ko: '홍경래의 난', title_hanja: '洪景來之亂',
    summary_html: '<p>평안도 차별과 세도 정치의 부패에 분노한 <strong>홍경래</strong>가 가산에서 봉기하여 청천강 이북을 한때 장악하였다. 정주성에서 4개월 농성 끝에 진압되었다.</p>',
    tags: ['홍경래', '평안도'] },
  // 헌종
  { king_id: 'heonjong', year: 1839, reign_year: 5, title_ko: '기해박해',
    summary_html: '<p>프랑스 신부 앵베르·모방·샤스탕과 신도 100여 명이 처형되었다. 정하상의 〈상재상서(上宰相書)〉가 이때 올려졌다.</p>',
    tags: ['천주교', '박해'] },
  // 철종
  { king_id: 'cheoljong', year: 1862, reign_year: 13, title_ko: '임술농민봉기',
    summary_html: '<p>진주에서 시작되어 삼남(三南) 70여 고을로 번진 농민 항쟁. 삼정(三政)의 문란이 직접 원인이었다.</p>',
    tags: ['임술', '농민봉기', '삼정'] },
  // 고종
  { king_id: 'gojong', year: 1866, reign_year: 3, title_ko: '병인양요 / 병인박해',
    summary_html: '<p>천주교에 대한 대탄압(병인박해)이 일어나고, 이를 빌미로 프랑스 함대가 강화도를 침공한 <strong>병인양요</strong>가 벌어졌다. 외규장각 도서가 약탈된다.</p>',
    tags: ['병인양요', '병인박해', '강화도'] },
  { king_id: 'gojong', year: 1871, reign_year: 8, title_ko: '신미양요 — 척화비',
    summary_html: '<p>제너럴 셔먼호 사건의 보복으로 미 함대가 강화 광성보를 공격하였다. 어재연 부대가 분전하였고, 흥선대원군은 전국에 <strong>척화비</strong>를 세웠다.</p>',
    tags: ['신미양요', '척화비'] },
  { king_id: 'gojong', year: 1876, reign_year: 13, title_ko: '강화도 조약', title_hanja: '江華島條約',
    summary_html: '<p>일본의 운요호 사건을 빌미로 체결된 조선 최초의 근대적 불평등 조약. 부산·원산·인천이 차례로 개항된다.</p>',
    tags: ['강화도조약', '개항'] },
  { king_id: 'gojong', year: 1882, reign_year: 19, title_ko: '임오군란',
    summary_html: '<p>구식 군인의 차별 대우에 분노한 봉기. 명성황후가 피신하고 흥선대원군이 일시 재집권하였으나 청군이 개입하여 진압하였다.</p>',
    tags: ['임오군란'] },
  { king_id: 'gojong', year: 1884, reign_year: 21, lunar_date: '10월 17일',
    title_ko: '갑신정변', title_hanja: '甲申政變',
    summary_html: '<p>김옥균·박영효 등 개화당이 우정총국 개국 축하연에서 거사하여 신정부를 세웠으나, 청군의 개입으로 <strong>3일 천하</strong>로 끝났다.</p>',
    tags: ['갑신정변', '김옥균', '개화당'] },
  { king_id: 'gojong', year: 1894, reign_year: 31, title_ko: '동학농민운동 · 갑오개혁',
    summary_html: '<p>전봉준이 이끄는 농민군이 봉기하여 전주 화약을 맺었다. 청·일이 이를 빌미로 전쟁(청일전쟁)을 벌였고, 갑오·을미 개혁이 단행되었다.</p>',
    tags: ['동학', '전봉준', '갑오개혁', '청일전쟁'] },
  { king_id: 'gojong', year: 1895, reign_year: 32, lunar_date: '8월 20일',
    title_ko: '을미사변 — 명성황후 시해', title_hanja: '乙未事變',
    summary_html: '<p>일본 공사 미우라(三浦) 등이 경복궁 건청궁에 난입하여 <strong>명성황후</strong>를 시해하였다. 단발령이 곧이어 내려져 의병이 일어났다.</p>',
    tags: ['을미사변', '명성황후'] },
  { king_id: 'gojong', year: 1897, reign_year: 34, lunar_date: '10월 12일',
    title_ko: '대한제국 선포', title_hanja: '大韓帝國',
    summary_html: '<p>고종이 환구단(圜丘壇)에서 황제 즉위식을 거행하고 국호를 <strong>대한제국</strong>, 연호를 <em>광무(光武)</em>로 정하였다.</p>',
    tags: ['대한제국', '광무'] },
  { king_id: 'gojong', year: 1905, reign_year: 42, lunar_date: '11월 17일',
    title_ko: '을사늑약',
    summary_html: '<p>일제가 외교권을 빼앗는 을사늑약을 강제 체결하였다. 황제의 비준 없이 이루어졌으며, 민영환이 자결하고 〈시일야방성대곡〉이 게재되었다.</p>',
    tags: ['을사늑약', '민영환', '시일야방성대곡'] },
  // 순종
  { king_id: 'sunjong', year: 1907, reign_year: 0, title_ko: '순종 즉위 / 군대 해산',
    summary_html: '<p>헤이그 특사 사건을 빌미로 고종이 강제 양위되고, 순종이 즉위하였다. 곧이어 한국 군대가 강제로 해산되어 의병 항쟁이 전국으로 번졌다.</p>',
    tags: ['헤이그', '군대 해산', '의병'] },
  { king_id: 'sunjong', year: 1909, reign_year: 3, lunar_date: '10월 26일',
    title_ko: '안중근 의거 — 하얼빈',
    summary_html: '<p><strong>안중근</strong> 의사가 하얼빈 역에서 이토 히로부미를 처단하였다. 이듬해 3월, 뤼순 감옥에서 순국하였다.</p>',
    tags: ['안중근', '이토 히로부미'] },
  { king_id: 'sunjong', year: 1910, reign_year: 4, lunar_date: '8월 29일',
    title_ko: '한일강제병합 — 조선왕조의 종말',
    summary_html: '<p>총리대신 이완용이 조약에 서명하니, 27대 519년에 걸친 조선왕조의 역사가 막을 내렸다.</p>',
    tags: ['병합', '경술국치'] },
];
